### ISSUE TITLE
the output file should be without empty spaces in the title 

### ISSUE THREAD

**Issue by leilaicruz** [Reza31415/Growth-Rate-Analysis#2]
hi @Reza31415  thanks for your software to compute exponential doubling times for a yeast population ! 

This issue refers to the fact that the output file the GUI generates right now has the following shape:
fitting_results  2021-05-19 12-47-38.txt

This filename has two empty spaces which sometimes generate problems for further processing if required, so I think you should just erase those empty spaces from the output file and put an underscore, like this:
fitting_results_2021-05-19_12-47-38.txt

**Comment by Reza31415** [comment]
Hi @leilaicruz . You're welcome.
The white spaces are now replaced by underline.
