### ISSUE TITLE
the mean and the std are unclear 

### ISSUE THREAD

**Issue by leilaicruz** [Reza31415/Growth-Rate-Analysis#3]
I had a hard time understanding your mean and std values output , and realized they correspond either to the whole column of values or the whole row, is that true?
OK , if that is so , then here you are assuming a case where the outer wells contain also cells which most of the cases you put control on them, so then the average is taking those values into account. 

Wouldn't solve the problem is you allow for certain template of strain names where you know the technical and biological replicates position in the plate in order to compute the mean and std over them and not to the entire column? 
Usually what we want to get out of the doubling time analysis is a mean and an error of an estimation over replicates of the same strain, or over the same condition .

**Comment by Reza31415** [comment]
This is a nice idea. I will implement it.

**Comment by Reza31415** [comment]
@leilaicruz There is now a table as a template to put the name of the strains on each well. After fitting, the results will be shown in a new table in the same tab. If you do not choose a name for a well, the corresponding statistics will appear under the name 'Wells with no name'.
In near future it will be possible to name a whole column or row in one go.

**Comment by leilaicruz** [comment]
ok , it is nice but still is kind of hard for the user , mainly if you have any strains in the plate, you can consider:
- importing a template with the names of the wells and with the name of the strains and media , like in a csv,namely, B2,yll3a,SC-ura+0% gal  so the user only enter this data once. Because suppose I fill up nicely your table and accidentally close the gui... I have to restart everything over ...really unfortunate situation ... haahha I think you can look at Werner's code for his GUI in Matlab that he had this implemented and perhaps give ideas , though I see you work with classes and objects while he doesn't. 
good luck! and this is a nice way to collaborate and interact in a software project , isnt it?

**Comment by Reza31415** [comment]
@leilaicruz I will implement importing an excel file and also saving the template if someone chooses to write it down in the GUI. Yes, GitHub looks nice for Software collaboration! I like it!
