### ISSUE TITLE
importing data command

### ISSUE THREAD

**Issue by leilaicruz** [Reza31415/Growth-Rate-Analysis#4]
I took me like 2 mins finding how to import the dataset into the GUI , because there was any button saying *Import data*, or *data* or something similar. Instead you use *Brows* which  I found hard to understand and its relation to that task. 
Could you rename this button in a more evident way that there is no doubt that this is used for importing the data?

**Comment by Reza31415** [comment]
The button 'brows' is now named 'Import Data'.
